language: node_js
node_js:
- '8'
sudo: required
services:
- docker
if: branch IN (master, develop)
install:
- npm i
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t drivereu/test-bed-time-service:$TRAVIS_BRANCH-latest .
- if [ $TRAVIS_BRANCH == "master" ]; then docker tag drivereu/test-bed-time-service:$TRAVIS_BRANCH-latest
  drivereu/test-bed-time-service:latest; fi
- if [ ! -z $TRAVIS_TAG ]; then docker tag drivereu/test-bed-time-service:$TRAVIS_BRANCH-latest
  drivereu/test-bed-time-service:$TRAVIS_TAG; fi
- docker push drivereu/test-bed-time-service
env:
  matrix:
  - secure: jY4g36OLli6uBIXADexy58KJF+mPVzwfsxpbm8PUMNAVg+8cxa5ZLm3AQsGDyNHb4M+OWZbnwTkbhutz04+e7q00nxIf4rp9Rm2eUsPCxbQarL2+6W0lbgLBPR63XtTfkYYwTnnPPsO8fsmYBgoB8q19I1aIA6vt7VzH9mMNR8a9HyogPEzQ5pOsgxBNKlUpAydLRMvXwZylnK7+w2N+BtlfZRsW+7D7WYWTczZgG95b2Zp8RV5TekhZT6lCVvTkDm5uv9WIjvuFucmEFuDU9FfyZLcnukk8Y72Te+TrQCs2YDR0XI8Lx6psK2n161WSTKPmQDy7zjD6Fj1lWVcTcaJ+qpo1nK3nkeQ3fWOWN8XRNVCVcD9yFPFMIO+iqsDLvwsgVqRVEXGmxB4eu9FD7rn92lC6TCoX1iWoUk8PpmFvdtMhOBZnjLP5eSDOmoGziR0FgRK9CLJ0sgpNx9uNV3QsXdW6vajwFBtNRNDrYNS8bLRcaBuwtdsC0zXHO4YHaB5ughObm6Dd14ConlF9/QEzdCYWAhu6N63xjMjM2GRtxNrSwvZMLbMIEejm1mFvg6UKgrihJ8+gSg90OAbmfEqy/D7amN7CU3vyRwwpoLXmUKQylMzttBv0zeQ/D6YCLiI4CkJkCDa+RZIYsavqU9ghjhaqzPviy6oCE/xRMf4=
  - secure: RjYWWGkIGcgud9n0VEJP6vE+/g4TVdAINhf6gmHXNfl37YCN9xIBSzRRTu1mI5AGQozJo+JAnMe2TvL1seMR6k34ZenYei2SIt7GB0cak+UCrsKyvWzpgRDS7yHSmr7kbg1qStDJE0pOTXu5G1LBEITtoK9HOSuYDMJxcxGA7sXFYDj76Xyd8R/KajIFQc0U6QJSK9PA8CxPh+ta5Jl69w3BKsydaYeVdCZ1OlP3a3LnyQaAPVdcuWl8JFkTyRlABej64lQeq14JVSC9TkVDBSUBmO5q25JMOfohg8PqaH+Sf4ACq69xw2aSLN8fH+CeFJySUmjNhhBJTggi/Nnnd0QhI8Q+gRTeIaczSpnV/h1/ZXjX0Npb6AMMY30AUoGzJpl/58qvdjy8+H154NkxZyxHAPT3F5z5lCDMG/LYbYGEh5yRer/WytjOKWKoympsnoop86JsttXqsAAEm53Xalx7vEXtwtd6EqEy7Ta6svvYMbgOeSRGSkWVconhb9J4f+npaLj7rZr9zepfZLhUCV9q17PzRD+GzCVnJ5Espf/9MSzJvW4dDPbYX4ATKOnffuMIOpuI6XDTTRzGAu8t5QnbFAU/M5z9ZhchxVAW/d4V6mhbBTKFus9lB2gwAI0IbgvJqS87656gAt5mr5g2bJ3FklNxaxnu6N189iHZjjM=
